### PR TITLE
Use image expando from stylesheet

### PR DESCRIPTION
**Pull request by TheTimeWalker**
See #141

### CODE REVIEW

**Comment by Jasius** [comment]
Dimensions not entirely correct on Edge w/RES

image

**Comment by TheTimeWalker** [comment]
Fixed, RES additionally uses max-width and max-height which forces it to keep 23x23 dimensions on all platforms. This should now be correct

**Review by Jasius — COMMENTED** [review]
I'll check it tonight, thanks.

**Comment by Jasius** [comment]
Still seems cut off 
image

**Review by Jasius — APPROVED** [review]
Good changes, thanks!

**Pull request merged**
