### PR TITLE
Add autoprefixer to gulpfile.js

### PR DESCRIPTION
**Pull request by idmarjr**
- Autoprefixer is compiling prefixed styles for the last 3 versions of major browsers;
- Souremaps is adding `.css.map` files into the `/dist/minified` folder;

### CODE REVIEW

**Review by Jasius — COMMENTED** [review]
Hey,

Any reason for adding source maps?

**Comment by idmarjr** [comment]
Hi @Jasius 
Well, technically by using sourcemaps you dont need to generate the non-minified since map files are going to point the correct line/column to each CSS declaration :)

I did not remove non-minified files in this pull request because they may be in use by someone.

But it's totally fine to do not have it :)

**Review by Jasius — COMMENTED** [review]
I see, I keep non minified files as a reference for those who aren't familiar with sass, they never get actually used. Source maps aren't really useful due to how reddit handles custom CSS.

image

**Comment by idmarjr** [comment]
I see your point. Gimme some minutes so I can remove sourcemaps :)

**Review by Jasius — COMMENTED** [review]
Cool, thank you @idmarjr

**Review by Jasius — APPROVED** [review]

**Pull request merged**
